# Use an official ARM64 Debian slim image as a parent image
FROM arm64v8/debian:bookworm-slim

LABEL org.opencontainers.image.authors = "tompisula@labrats.work"
LABEL org.opencontainers.image.source = "https://github.com/labrats-work/ops-images"

# Avoid prompts from apt
ENV DEBIAN_FRONTEND=noninteractive

# Install necessary packages for Ansible and Git
RUN apt-get update && \
    apt-get install -y python3 python3-pip git && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Upgrade pip and Install Ansible using pip
RUN python3 -m pip install --upgrade pip && \
    python3 -m pip install ansible


# Set the working directory in the container
WORKDIR /usr/src/app

# Copy the script into the container at /usr/src/app
COPY entrypoint.sh .
COPY repo_sync.sh .

# Make the script executable
RUN chmod +x entrypoint.sh

# Use the entry script to initialize the container
ENTRYPOINT ["./entrypoint.sh"]
