FROM docker.io/alpine:3

LABEL org.opencontainers.image.authors = "tompisula@labrats.work"
LABEL org.opencontainers.image.source = "https://github.com/labrats-work/ops-images"

RUN apk add --no-cache \
    terraform \
    tar \
    git \
    openssh \
    python3 \
    py3-pip \
    jq \
    yq \
    && pip3 install --upgrade pip \
    && pip3 install ansible

WORKDIR /app

ENTRYPOINT []
CMD []