FROM docker.io/alpine:3

LABEL org.opencontainers.image.authors="tompisula@labrats.work"

RUN apk add --no-cache \
    terraform \
    ansible \
    openssh \
    python3 \
    py3-pip \
    && pip3 install --upgrade pip

WORKDIR /app

ENTRYPOINT []
CMD []