# Use an official AMD64 Debian slim image as a parent image
FROM arm64v8/debian:bookworm-slim

LABEL org.opencontainers.image.authors="tompisula@labrats.work"
LABEL org.opencontainers.image.source="https://github.com/labrats-work/ops-images"

# Install Python, pip, and venv
RUN apt-get update && \
    apt-get install -y python3 python3-pip python3-venv git wireguard iproute2 openresolv procps curl libicu72 && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Create a virtual environment
RUN python3 -m venv /opt/venv

# Install Ansible within the virtual environment
ENV PATH="/opt/venv/bin:$PATH"
RUN pip install --upgrade pip && \
    pip install ansible

# Set the working directory in the container
WORKDIR /usr/src/app

# Copy the scripts into the container at /usr/src/app
# Ensure they are owned by the non-root user
COPY run.sh .

# Make the runner
RUN curl -o actions-runner-linux-arm64-2.314.1.tar.gz -L https://github.com/actions/runner/releases/download/v2.314.1/actions-runner-linux-arm64-2.314.1.tar.gz
RUN echo "3d27b1340086115a118e28628a11ae727ecc6b857430c4b1b6cbe64f1f3b6789  actions-runner-linux-arm64-2.314.1.tar.gz" | shasum -a 256 -c
RUN tar xzf ./actions-runner-linux-arm64-2.314.1.tar.gz
RUN rm actions-runner-linux-arm64-2.314.1.tar.gz

RUN groupadd -r ghagent && useradd -r -g ghagent ghagent

RUN chown -R ghagent:ghagent /usr/src/app

USER ghagent

# Use the entry script to initialize the container
ENTRYPOINT ["./run.sh"]
