FROM docker.io/alpine:3

LABEL org.opencontainers.image.authors = "tompisula@labrats.work"
LABEL org.opencontainers.image.source = "https://github.com/labrats-work/ops-images"

ARG TERRAFORM_VERSION=1.6.6

RUN apk add --no-cache \
    xorriso \
    git \
    curl \
    openssh \
    python3 \
    py3-pip \
    jq \
    yq \
    && pip3 install --upgrade pip

RUN curl -LO https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip \
    && unzip terraform_${TERRAFORM_VERSION}_linux_amd64.zip -d /usr/local/bin \
    && rm terraform_${TERRAFORM_VERSION}_linux_amd64.zip

WORKDIR /app

ENTRYPOINT []
CMD []
