FROM python:3.8-slim
RUN apt-get update \
    && apt-get install -y --no-install-recommends build-essential gcc ffmpeg \
    && rm -rf /var/lib/apt/lists/*

RUN pip3 install --upgrade pip

ENTRYPOINT []
CMD []