FROM registry.hub.docker.com/library/python:3.9-slim-buster
RUN apt-get update \
    && apt-get install -y --no-install-recommends build-essential gcc ffmpeg \
    && rm -rf /var/lib/apt/lists/*

RUN pip3 install --upgrade pip

ENTRYPOINT []
CMD []