# Use an official AMD64 Debian slim image as a parent image
FROM amd64/debian:bookworm-slim

LABEL org.opencontainers.image.authors="tompisula@labrats.work"
LABEL org.opencontainers.image.source="https://github.com/labrats-work/ops-images"

# Install Python, pip, and venv
RUN apt-get update && \
    apt-get install -y python3 python3-pip python3-venv git wireguard && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Create a virtual environment
RUN python3 -m venv /opt/venv

# Install Ansible within the virtual environment
ENV PATH="/opt/venv/bin:$PATH"
RUN pip install --upgrade pip && \
    pip install ansible

# Set the working directory in the container
WORKDIR /usr/src/app

# Copy the scripts into the container at /usr/src/app
# Ensure they are owned by the non-root user
COPY entrypoint.sh .
COPY repo_sync.sh .

# Make the scripts executable
RUN chmod +x entrypoint.sh repo_sync.sh

# Use the entry script to initialize the container
ENTRYPOINT ["./entrypoint.sh"]
