# Container image that runs your code
FROM docker.io/alpine:3

LABEL org.opencontainers.image.authors = "tompisula@labrats.work"
LABEL org.opencontainers.image.source = "https://github.com/labrats-work/ops-images"


RUN apk -U upgrade
# Generic pre-req
RUN apk add curl git openssh
# Ansible pre-req
RUN apk add python3
# Ansible
RUN apk add ansible

ENTRYPOINT [""]