FROM docker.io/alpine:3

LABEL org.opencontainers.image.authors = "tompisula@labrats.work"
LABEL org.opencontainers.image.source = "https://github.com/labrats-work/ops-images"

RUN apk add --no-cache \
    ansible \
    git \
    openssh \
    python3 \
    py3-pip \
    && pip3 install --upgrade pip

WORKDIR /app

ENTRYPOINT []
CMD []