name: 'ansible'

on:
  push:
    # branches:
    #   - "main"
  workflow_dispatch:

jobs:
  build-and-test:
    uses: ./.github/workflows/build.yml
    with:
      context: ./src/ansible
      registry_image: ghcr.io/${{ github.repository }}/ansible
    secrets: inherit