name: Create and publish a Docker image

on: 
  push:
  schedule:
    - cron: '0 0 * * 1'

env:
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}

jobs:
  build-and-push-amd64-image:
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        image: [ terraform, ansible, python, python-ffmpeg ]

    permissions:
      contents: read
      packages: write    

    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }} 

      - name: Login to DockerHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }} 

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./src/${{ matrix.image }}
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/${{ matrix.image }}:latest
            docker.io/labratswork/ops-images-${{ matrix.image }}:latest