name: 'omnibus-tests'
  
on:
  workflow_call:
    inputs:
      image-tag:
        type: string
        description: 'The tag of the omnibus image to use for testing'
        required: true
        default: 'main'

jobs:
  run-image:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/labrats-work/ops-images/omnibus:${{ inputs.image-tag }}
      options: --cap-add NET_ADMIN --cap-add SYS_MODULE --sysctl net.ipv4.conf.all.src_valid_mark=1
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    steps:
    - 
      name: Terraform CLI
      run: |
        terraform -v
    
