name: 'omnibus-tests'
  
on:
  workflow_call:
    inputs:
      image-tag:
        type: string
        description: 'The tag of the omnibus image to use for testing'
        required: true
        default: 'main'

jobs:
  run-amd64:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/labrats-work/ops-images/omnibus:${{ inputs.image-tag }}
      options: --platform linux/amd64 --cap-add NET_ADMIN --cap-add SYS_MODULE --sysctl net.ipv4.conf.all.src_valid_mark=1
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    steps:
    - 
      name: Terraform
      run: |
        which terraform
        terraform -v
    - 
      name: Ansible
      run: |
        which ansible
        ansible --version
    - 
      name: Python
      run: |
        which python
        python --version
    - 
      name: Wireguard
      run: |
        which wg
        which wg-quick

  run-arm64v8:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/labrats-work/ops-images/omnibus:${{ inputs.image-tag }}
      options: --platform linux/arm64/v8 --cap-add NET_ADMIN --cap-add SYS_MODULE --sysctl net.ipv4.conf.all.src_valid_mark=1
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    steps:
    - 
      name: Terraform
      run: |
        which terraform
        terraform -v
    - 
      name: Ansible
      run: |
        which ansible
        ansible --version
    - 
      name: Python
      run: |
        which python
        python --version
    - 
      name: Wireguard
      run: |
        which wg
        which wg-quick
    
