name: 'omnibus-tests'
  
on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: 'The tag of the omnibus image to use for testing'
        required: true
        default: 'latest'

jobs:
  common:
    runs-on: ubuntu-latest
    environment: ${{ github.workflow }}

    container:
      image: ghcr.io/labrats-work/ops-images/omnibus:${{ github.event.inputs.image_tag }}
      options: --cap-add NET_ADMIN --cap-add SYS_MODULE --sysctl net.ipv4.conf.all.src_valid_mark=1

    steps:
    - 
      name: Terraform CLI
      run: |
        terraform -v
    
