name: 'omnibus-tests'
  
on:
  workflow_call:
    inputs:
      image-tag:
        type: string
        description: 'The tag of the omnibus image to use for testing'
        required: true
        default: 'main'

jobs:
  run-amd64:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch:
          - docker: linux/amd64 
          - docker: linux/arm64/v8

    steps:
    - 
      name: Set up QEMU
      uses: docker/setup-qemu-action@v1
      with:
        platforms: ${{ matrix.arch }}

    - 
      name: Run in Docker
      run: |
        docker run \
          --rm \
          -v $(pwd):/${{ github.workspace }} \
          -w ${{ github.workspace }} \
          --platform ${{ matrix.arch }} \
          ghcr.io/labrats-work/ops-images/omnibus:${{ inputs.image-tag }} \
          uname -a
    - 
      name: Terraform
      run: |
        echo $(which terraform)
        terraform -v
    - 
      name: Ansible
      run: |
        echo $(which ansible)
        ansible --version
    - 
      name: Python
      run: |
        echo $(which python)
        python --version
    - 
      name: Wireguard
      run: |
        echo $(which wg)
        which wg-quick
    
