name: 'omnibus'

on:
  push:
    # branches:
    #   - "main"
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      context: ./src/omnibus
      registry_image: ghcr.io/${{ github.repository }}/omnibus
    secrets: inherit

  test:
    uses: ./.github/workflows/test.yml
    needs: build
    with:
      context: ./src/omnibus
      registry_image: ghcr.io/${{ github.repository }}/omnibus
    secrets: inherit