name: 'python-ffmpeg'

on:
  push:
    # branches:
    #   - "main"
  workflow_dispatch:

jobs:
  build-and-test:
    uses: ./.github/workflows/build.yml
    with:
      context: ./src/python-ffmpeg
      registry_image: ghcr.io/${{ github.repository }}/python-ffmpeg
    secrets: inherit