name: 'terraform'

on:
  push:
    # branches:
    #   - "main"
  workflow_dispatch:

jobs:
  build-and-test:
    uses: ./.github/workflows/build.yml
    with:
      context: ./src/terraform
      registry_image: ghcr.io/${{ github.repository }}/terraform
    secrets: inherit